from django.urls import path

from .views import (
    AddSetToExerciseView,
    SetDetailView,
    ToggleSetDoneView,
    WorkoutDetailView,
    WorkoutFinishView,
    WorkoutListView,
    WorkoutProgramDayAddExerciseView,
    WorkoutProgramDayDetailView,
    WorkoutProgramDayListView,
    WorkoutProgramDayStartView,
    WorkoutProgramDetailView,
    WorkoutProgramExerciseAddSetView,
    WorkoutProgramExerciseDeleteView,
    WorkoutProgramListView,
    WorkoutProgramSetDetailView,
)

app_name = 'diary'

urlpatterns = [
    path('workouts/',
         WorkoutListView.as_view(),
         name='workout_list'),
    path('workouts/<int:pk>/',
         WorkoutDetailView.as_view(),
         name='workout_detail'),
    path('workouts/<int:pk>/finish/',
         WorkoutFinishView.as_view(),
         name='finish_workout'),
    path('workout-exercises/<int:pk>/sets/',
         AddSetToExerciseView.as_view(),
         name='add_set'),
    path('sets/<int:pk>/',
         SetDetailView.as_view(),
         name='update_set'),
    path('sets/<int:pk>/toggle/',
         ToggleSetDoneView.as_view(),
         name='toggle_set_done'),
    path('default-workouts/',
         WorkoutProgramListView.as_view(),
         name='create_template'),
    path('default-workouts/<int:pk>/',
         WorkoutProgramDetailView.as_view(),
         name='template_detail'),
    path('default-workouts/<int:pk>/days/',
         WorkoutProgramDayListView.as_view(),
         name='create_template_day'),
    path('default-workouts/<int:pk>/days/<int:dpk>/',
         WorkoutProgramDayDetailView.as_view(),
         name='template_day_detail'),
    path('default-workouts/<int:pk>/days/<int:dpk>/exercises/',
         WorkoutProgramDayAddExerciseView.as_view(),
         name='add_template_exercise'),
    path('default-workouts/<int:pk>/days/<int:dpk>/start/',
         WorkoutProgramDayStartView.as_view(),
         name='start_from_template_day'),
    path('default-workout-exercises/<int:pk>/',
         WorkoutProgramExerciseDeleteView.as_view(),
         name='delete_template_exercise'),
    path('default-workout-exercises/<int:pk>/sets/',
         WorkoutProgramExerciseAddSetView.as_view(),
         name='add_template_set'),
    path('default-workout-sets/<int:pk>/',
         WorkoutProgramSetDetailView.as_view(),
         name='update_template_set'),
]
