from django.urls import path

from .views import (
    CreatePresetSmartWorkoutProgramView,
    SmartWorkoutProgramDayAddExerciseView,
    SmartWorkoutProgramDayDetailView,
    SmartWorkoutProgramDayExerciseAddSetView,
    SmartWorkoutProgramDayExerciseDeleteView,
    SmartWorkoutProgramDayListView,
    SmartWorkoutProgramDayStartView,
    SmartWorkoutProgramDetailView,
    SmartWorkoutProgramListView,
    SmartWorkoutProgramSetDetailView,
    SmartWorkoutSessionDetailView,
    SmartWorkoutSessionFinishView,
    SmartWorkoutSessionResultsView,
    SmartWorkoutSetUpdateView,
)

app_name = 'smart_workout'

urlpatterns = [
    path('smart-workouts/create-preset/',
         CreatePresetSmartWorkoutProgramView.as_view(),
         name='create_preset_program'),
    path('smart-workouts/',
         SmartWorkoutProgramListView.as_view(),
         name='program_list'),
    path('smart-workouts/<int:pk>/',
         SmartWorkoutProgramDetailView.as_view(),
         name='program_detail'),
    path('smart-workouts/<int:pk>/days/',
         SmartWorkoutProgramDayListView.as_view(),
         name='day_list'),
    path('smart-workouts/<int:pk>/days/<int:bpk>/',
         SmartWorkoutProgramDayDetailView.as_view(),
         name='day_detail'),
    path('smart-workouts/<int:pk>/days/<int:bpk>/exercises/',
         SmartWorkoutProgramDayAddExerciseView.as_view(),
         name='day_add_exercise'),
    path('smart-workouts/<int:pk>/days/<int:bpk>/start/',
         SmartWorkoutProgramDayStartView.as_view(),
         name='start_day_workout'),
    path('smart-workout-exercises/<int:be_pk>/',
         SmartWorkoutProgramDayExerciseDeleteView.as_view(),
         name='day_exercise_delete'),
    path('smart-workout-exercises/<int:be_pk>/sets/',
         SmartWorkoutProgramDayExerciseAddSetView.as_view(),
         name='day_exercise_add_set'),
    path('smart-workout-sets/<int:bs_pk>/',
         SmartWorkoutProgramSetDetailView.as_view(),
         name='day_set_detail'),
    path('smart-workout-sessions/<int:spk>/',
         SmartWorkoutSessionDetailView.as_view(),
         name='program_workout_detail'),
    path('smart-workout-sessions/<int:spk>/finish/',
         SmartWorkoutSessionFinishView.as_view(),
         name='finish_program_session'),
    path('smart-workout-sessions/<int:spk>/results/',
         SmartWorkoutSessionResultsView.as_view(),
         name='progression_results'),
    path('smart-workout-sets/<int:set_pk>/update/',
         SmartWorkoutSetUpdateView.as_view(),
         name='program_set_update'),
]
