# Generated by Django 5.2.5 on 2026-04-13 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_exercisemusclegroup_alter_exercise_muscle_groups'),
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SmartBlockExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='smart_workout.smartblock')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_block_exercises', to='catalog.exercise')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('block', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='SmartProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='smartblock',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='smart_workout.smartprogram'),
        ),
        migrations.CreateModel(
            name='SmartProgressionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('new_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.CharField(choices=[('increase', 'Увеличение'), ('maintain', 'Сохранение'), ('decrease', 'Снижение'), ('deload', 'Разгрузка')], max_length=20)),
                ('sets_completed', models.PositiveIntegerField()),
                ('avg_reps', models.DecimalField(decimal_places=1, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_logs', to='smart_workout.smartblockexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_progression_logs', to='diary.trainingsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='smart_workout.smartblock')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='smart_workout.smartprogram')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_session', to='diary.trainingsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reps', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='smart_workout.smartblockexercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
